import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Modal } from '@/src/components/Modal'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
   const  [open, setOpen] = useState(false)
   console.log("resultou", open)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
           <h2>Clique no botão</h2>
           <button onClick={()=>setOpen(!open)} >Clique em min</button>          
        </div>
        <Modal isOpen={open} setOpen={setOpen} />

      </main>
    </>
  )


}
